version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: rheasamuel/flask_iss_tracker:1.0
        container_name: flask_iss_tracker
        ports:
            - "5000:5000"
